require('dotenv').config()

const MONGODB_URI = process.env.MONGODB_URI;
const PORT = process.env.PORT;
const MODE = process.env.NODE_ENV;
const ORIGIN = process.env.ORIGIN;
const TRANSPORTER_EMAIL_USER = process.env.TRANSPORTER_EMAIL_USER;
const TRANSPORTER_EMAIL_PASS = process.env.TRANSPORTER_EMAIL_PASS;
const TRANSPORTER_EMAIL_HOST = process.env.TRANSPORTER_EMAIL_HOST;
const TRANSPORTER_EMAIL_PORT = process.env.TRANSPORTER_EMAIL_PORT;

module.exports = {
    MONGODB_URI,
    PORT,
    MODE,
    ORIGIN,
    TRANSPORTER_EMAIL_USER,
    TRANSPORTER_EMAIL_PASS,
    TRANSPORTER_EMAIL_HOST,
    TRANSPORTER_EMAIL_PORT
}