name: Dockerize on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t your-docker-image-name .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag your-docker-image-name ghcr.io/your-github-username/your-docker-image-name:latest

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/your-github-username/your-docker-image-name:latest
