name: Dockerize on Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t dicentumbackend .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag dicentumbackend ghcr.io/pabpercab1/dicentumbackend:latest

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/pabpercab1/dicentumbackend:latest
